# Theme
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "mint"

# Site
locale: "tr-TR"
title: "Ali Yalçınkaya - İstatistiksel Danışmanlık"
title_separator: "—"
url: "https://ali-yalcinkaya.github.io"
baseurl: "/istatistik"
repository: "ali-yalcinkaya/istatistik"
teaser: "/assets/images/teaser.jpg"
logo: "/assets/images/logo.png"  # varsa logoyu aç

# SEO
plugins:
  - jekyll-seo-tag     # ÖNEMLİ: SEO meta etiketleri
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-paginate

# Analytics
analytics:
  provider: "google-gtag"
  google:
    tracking_id: ""       # G-XXXX... (ekle)
    anonymize_ip: true

# Open Graph / Sosyal
og_image: "/assets/images/site-og.jpg"  # 1200x630 önerilir
twitter:
  card: "summary_large_image"
  username: ""  # varsa ekle

# Author
author:
  name: "Dr. Ali Yalçınkaya"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "İstatistiksel Danışman | Veri Analizi Uzmanı | R, Python & SPSS Specialist"
  location: "İstanbul, Türkiye"
  email: "info@aliyalcinkaya.com"
  links:
    - label: "E-posta"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:info@aliyalcinkaya.com"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/profiliniz"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=ID"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ali-yalcinkaya"
    - label: "ResearchGate"
      icon: "fab fa-fw fa-researchgate"
      url: "https://www.researchgate.net/profile/profiliniz"

# Arama (Lunr, eklentisiz çalışır)
search: true
enable_copy_code_button: true
breadcrumbs: true

# Çıktı / Zaman dilimi
timezone: "Europe/Istanbul"
permalink: /:categories/:title/

# Pagination
paginate: 9
paginate_path: /sayfa:num/

# Varsayılanlar
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# GitHub Pages safe ile uyum
whitelist:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-paginate
  
exclude:
  - docs
  - test
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - node_modules
  - package.json
  - package-lock.json
  - README
  - tmp

